config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'dashboard#index', :as => :authenticated_root
    # resources :sports, :only => [:show]
  end


  root 'welcome#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :dashboard
  resources :users, :only => [:show]
  resources :sports do
    resources :teams do
      resources :players
    end
  end

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  accepts_nested_attributes_for :team

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :teams
  has_many :players, :through => :teams
  accepts_nested_attributes_for :teams

end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :sport
  has_many :players
  accepts_nested_attributes_for :sport, :players

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :address
    devise_parameter_sanitizer.for(:account_update) << :city
    devise_parameter_sanitizer.for(:account_update) << :state
    devise_parameter_sanitizer.for(:account_update) << :zipcode
    devise_parameter_sanitizer.for(:account_update) << :avatar
    # devise_parameter_sanitizer.for(:account_update) { |u| u.permit( :name, :address, :city, :state, :zipcode, :avatar) }
end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 def index
  @teams = Team.all
  @sports = Sport.all
  # @sports_teams = Team.where(sport_id: sport.id)
  @players = Player.all

 end

  def show
    # if @profile != nil
    #   @profile = Profile.find(current_user.id)
    # else
    #   @profile = Profile.create({:user_id => current_user.id})
    #   @profile = Profile.find_by(user_id: current_user.id)
    # end
  end

  private

  # def find_profile
  #   @profile = Profile.find_by(user_id: current_user.id)
  # end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:team_id])
    @players = Player.where(:team_id => @team.id)

  end

  def new
    @team = Team.find(params[:team_id])
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      flash[:notice] = "Contact created."
      redirect_to sport_team_players_path
    else
      render 'new'
    end
  end

  def show
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
    @team = Team.find(params[:team_id])
  end

  def update
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    if @player.update(player_params)
      flash[:notice] = "Contact updated."
      redirect_to sport_team_player_path(@sport.id, @team.id, @player.id)

    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:team_id])
    @player = Player.find(params[:id])
    @player.destroy
    flash[:notice] = "Contact deleted."
    redirect_to sport_team_players_path
  end

   private
  def player_params
    params.require(:player).permit(:first_name, :last_name, :number, :position, :team_id, :id)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      flash[:notice] = "Contact created."
      redirect_to sports_path
    else
      render 'new'
    end
  end

  def show
    @sport = Sport.find(params[:id])
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:id])
    if @sport.update(sport_params)
      flash[:notice] = "Contact updated."
      redirect_to sport_path(@sport)
    else
      render 'edit'
    end
  end

  def destroy
    @sport = Sport.find(params[:id])
    @sport.destroy
    flash[:notice] = "Contact deleted."
    redirect_to sports_path
  end

   private
  def sport_params
    params.require(:sport).permit(:name, :id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @sport = Sport.find(params[:sport_id])
    @teams = Team.where(:sport_id => @sport.id)
  end

  def new
    @sport = Sport.find(params[:sport_id])
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:notice] = "Contact created."
      redirect_to sport_teams_path
    else
      render 'new'
    end
  end

  def show
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
  end

  def edit
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
  end

  def update
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
    if @team.update(team_params)
      flash[:notice] = "Contact updated."
      redirect_to sport_team_path(@sport.id, @team.id)

    else
      render 'edit'
    end
  end

  def destroy
    @sport = Sport.find(params[:sport_id])
    @team = Team.find(params[:id])
    @team.destroy
    flash[:notice] = "Contact deleted."
    redirect_to sport_teams_path
  end

   private
  def team_params
    params.require(:team).permit(:name, :id, :sport_id, :city, :state, :zipcode, :team_id)
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1> This is the page that allows you to do everything</h1>


<% if current_user.admin? %>
<p> USER IS ADMIN TRUE </P>
<span><h2> SELECT A TEAM TO EDIT </h2>
    <% @sports.each do |sport| %>
      <%= sport.name %>
      <ul>
        <% @teams.where(sport_id: sport.id).each do |team| %>
          <li><%= link_to team.name, sport_team_path(team.sport_id, team.id) %> || <%= link_to "Players", sport_team_players_path(team.sport_id, team.id)%></li>
        <% end %>
      </ul>
    <% end %>
<%= link_to "Add a new sport", sports_path, :class=> "btn btn-default" %>

<h2> CURRENT SPORTS SUPPORTED


  <% else %>
<p> NORMAL USER </p>
<% end %>
<%= link_to "Add a Sport to application", sports_path, :class=> "btn btn-default" %>

app/views/dashboard/show.html.erb
<h1> Pick a sport/team you are interested in following </h1>

<h2> To follow a new team, click here</h2>
<p> List all sports </p>
<p> List all teams </p>

<h2> To go to a team you are following, click here </h2>
<p> List all teams that you are currently 'following' </p>

<h2> To see your past games and history, click here </h2>
<p> View points and redeemabiity, by team? </p>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-2 navbar-brand">
        <a href="/">Home</a>
      </div>
      <div class="col-md-8">
        <ul class="nav nav-pills">
          <li><a href="#">About Us</a></li>
          <li><a href="#">Terms</a></li>
          <li><a href="#">Support</a></li>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-lg" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-02" toggle="">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="/"><span>Pickaplayer</span></a>
  </div>

  <div class="collapse navbar-collapse" id="#navbar-collapse-02">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><p class="navbar-text"><span class="label label-primary">Signed in as <%= current_user.email %></span></p></li>
      <li class="dropdown">
        <div class="btn-group">
          <button class="btn btn-primary btn-sm navbar-btn btn-embossed dropdown-toggle" data-toggle="dropdown">
            <span class="fui-user" style="visibility: hidden;"></span><span class="caret">
          </button>
          <span class="dropdown-arrow"></span>
          <ul class="dropdown-menu">
            <li><a href="#">My Points</a></li>
            <li><a href="#">Shop/Redeem</a></li>
            <li class="divider"></li>
            <li><%= link_to "Sports", sports_path%></li>
            <li><%= link_to "Home", root_path%></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </li>
      <% else %>
      <li>
         <%= button_to " Sign up " , new_user_registration_path, :class => 'btn btn-sm btn-block btn-success navbar-btn btn-embossed', method: :get %>
       </li>
       <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
        <li>
            <%= button_to "Login", new_user_session_path, :class => 'btn btn-sm btn-block btn-primary navbar-btn btn-embossed', method: :get %>
         </li>
      <% end %>
      <li><a href="#"><span class="visible-sm visible-xs">Settings<span class="fui-gear"></span></span><span class="visible-md visible-lg"><span class="fui-gear"></span></span></a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav><!-- /navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render("layouts/navbar") %>
<div class="container">
  <%= flash[:alert] %>
  <%= flash[:notice] %>
<%= yield %>

<%= render("layouts/footer") %>

</div>
</body>
</html>

app/views/players/_form.html.erb
<% if @player.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @player.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@player, :url => sport_team_players_path) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
  <div class="form-group">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="form-group">
     <%= f.hidden_field :team_id, :value => @team.id %></br>
   </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/players/_formedit.html.erb
<% if @player.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @player.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@player, :url => sport_team_player_path) do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>
  <div class="form-group">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="form-group">
     <%= f.hidden_field :team_id, :value => @team.id %></br>
   </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/players/edit.html.erb
<%= content_for(:title, "Edit Player | Pickaplayer") %>

<h1>Edit Player</h1>

<%= render 'formedit' %>

app/views/players/index.html.erb
<%= content_for(:title, "#{@team.name}| Pickaplayer") %>

<h1> <%=@team.name + " Team Roster" %> </h1>
<ul>
<% @players.each do |player| %>
  <li><%=link_to player.first_name + " " + player.last_name, sport_team_player_path(@sport.id, @team.id, player.id) %> | |
      <%= link_to "Delete", sport_team_player_path(@sport.id, @team.id, player.id),
              :confirm => "You sure?",
              :method => "delete" %></li>
  <% end %>
</ul>

<p> <%= link_to "Add players to #{@team.name}", new_sport_team_player_path(@sport.id, @team.id) %></p>

<p> <%= link_to "Back to Other Teams", sport_teams_path %></p>

app/views/players/new.html.erb
<%= content_for(:title, "New Player | Pickaplayer") %>

<h1>New Player</h1>

<%= render 'form' %>

app/views/players/show.html.erb
<h1><%= @player.first_name + " " + @player.last_name %> </h1>


<p>Number: <%= @player.number %></p>

<p>Position: <%= @player.position%></p>




<p> <%= link_to "Edit", edit_sport_team_player_path %></p>


<p><%= link_to "Back", sport_team_players_path %></p>

app/views/sports/_form.html.erb
<% if @sport.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @sport.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@sport) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/sports/edit.html.erb
<%= content_for(:title, "Edit Sport | Pickaplayer") %>

<h1>Edit Sport</h1>

<%= render 'form' %>

app/views/sports/index.html.erb
<h1> Sports Index Page </h1>

<ul>
<% @sports.each do |sport| %>
  <li><%=link_to "#{sport.name}", sport_path(sport) %> | |
      <%= link_to "Delete", sport_path(sport),
              :confirm => "You sure?",
              :method => "delete" %></li>
  <% end %>
</ul>
<%= link_to "New sport", new_sport_path, :class=> "btn btn-default" %>

app/views/sports/new.html.erb
<%= content_for(:title, "New Sport | Pickaplayer") %>

<h1>New Sport</h1>

<%= render 'form' %>

app/views/sports/show.html.erb
<h1> <%= @sport.name %> </h1>

<p> <%= link_to "See all #{@sport.name} teams", sport_teams_path(@sport.id) %></p>

<p> <%= link_to "Create new " + @sport.name + " team", new_sport_team_path(@sport.id) %></p>


<p> <%= link_to "Edit", edit_sport_path %></p>


<p><%= link_to "Back", sports_path %></p>

app/views/welcome/index.html.erb
<h1> Welcome to PickaPlayer </h1>

<p> Pick a sport you are interested in following</p>
<p> ajax into teams -- Pick a team</p>
<p> Then goes to login </p>

Login takes team argument and